### ISSUE TITLE
autofocus attribute causes chaos on the select dropdown 

### ISSUE THREAD

**Issue by jrh418** [ngbolt/ng-bolt#30]
If you create a blt-dropdown (type: select) and set the autofocus, it will cause a nested repeat.

ctrl.options = { "foo": "Foo", "bar": "Bar, "foobar": "Foo Bar"}

Should Produce:
* Foo
* Bar
* Foo Bar

With the autofocus, will produce:
* Foo
* Foo
* Foo
* Bar
* Bar
* Bar
* Foo Bar
* Foo Bar
* Foo Bar

**Comment by theJuddson** [comment]
This issue is being resolved by the refactoring effort in issue #49.
