### ISSUE TITLE
fix hover padding in docs menu

### ISSUE THREAD

**Issue by kms6427** [ngbolt/ng-bolt#31]
Remove the awkward padding that the darker hover color strip has whenever the mouse hovers over an item on the menu. The hover color should darken the entire menu item you're hovering over.

**Comment by theJuddson** [comment]
This is in reference to the top/bottom padding on each menu item in the "Guides" section of the ng-bolt documentation: https://ngbolt.github.io/#/guides. Hover over "Introduction" to observe.
![padding](https://cloud.githubusercontent.com/assets/10535198/26353612/44abd0a0-3f8f-11e7-875c-9390fdbb64f8.png)

**Comment by theJuddson** [comment]
Fixed in `development` branch.
