### ISSUE TITLE
"blt-required" does not update with dynamic data

### ISSUE THREAD

**Issue by GeoQDeveloper** [ngbolt/ng-bolt#34]
With dynamic data, like {{Main.isRequired}}, the "data-required" directive on the "blt-textfield" component fails to update properly if the dynamic value is "true" at first.

Static values, like "true" or "false," work fine, as does any evaluation where the initial value is false.

The current workaround is to use {{isTimeoutExpired && Main.isRequired}}, where isTimeoutExpired is set with $scope.isTimeoutExpired = false; $timeout(function() {$scope.isTimeoutExpired = true;}, 1000);  In this way, the bug is avoided because the "data-required" field initializes to false at first.

If data-required is "true" at first, then the user can never submit the form because validation continues to be performed when it isn't desired.

**Comment by theJuddson** [comment]
This issue is being resolved by the refactoring effort in issue #49.
