### ISSUE TITLE
Change blt-datepicker to append date selection to document

### ISSUE THREAD

**Issue by GeoQDeveloper** [ngbolt/ng-bolt#38]
The blt-datepicker component currently creates new DOM elements inside the same parent where the text field containing the datepicker's data is located.

When a large element is the parent, there is no difference, but when the parent element is small, like a small modal dialog, scrollbars appear and the user can't select all the years and months, since they are hidden out of view.  By "can't select," I mean that it's actually not possible to select them, because clicking on the scrollbars to advance the page right or down causes the datepicker to close.  Using a higher "z-index" does not resolve this problem.

The issue can be resolved by having blt-datepicker append the datepicker's controls to the document.  That way, the datepicker will only be truncated if it appears off the side of the browser window, and will not be incorrectly contained by other elements.

**Comment by GeoQDeveloper** [comment]
The datepicker also leaves scrollbars present even after it is closed, once it has been opened for the first time inside an element that is too small.

**Comment by jrh418** [comment]
This only occurs when the datepicker was placed in the wrong type of element.
