### ISSUE TITLE
"Max length" attribute does not work on text areas

### ISSUE THREAD

**Issue by mgramigna** [ngbolt/ng-bolt#51]
In the [docs for bltTextField](https://ngbolt.github.io/#/api/blt_textfield/directive/bltTextField), there is an attribute called "data-maxlength" that is supposed to limit the number of characters a user can enter in a text field. When data-type="textarea" on that text field, this property does not work. It also does not work on the "comments field" demo on the docs page.

**Comment by theJuddson** [comment]
Thanks, we've verified the issue in our current release branch. This has been fixed by some related work currently in a development branch and will be included in our v2.1.0 release sometime this week.

**Comment by theJuddson** [comment]
Fixed in v3.0.0
